#+TITLE: Bookmarks / Links

* Kindle unlimited catalog of elegible books:

https://www.amazon.com/b?node=9069934011&tag=efly01-20


* github

Configuring user and password with Git Bash
https://stackoverflow.com/questions/8840551/configuring-user-and-password-with-git-bash

How to save username and password in GIT [GitExtension]?
https://stackoverflow.com/questions/35942754/how-to-save-username-and-password-in-git-gitextension

https://levelup.gitconnected.com/5-technologies-to-pick-up-during-quarantine-and-improve-your-software-engineering-skillset-68bd766bee9c


* OReilly

21 Technologies for the 21st Century
https://learning.oreilly.com/library/view/21-technologies-for/9781492090298/ch01.html


EntrePreneurship list
https://learning.oreilly.com/playlists/deb1ae06-6506-4362-b8da-ee71c72f306a/

Lessons from Giants
https://learning.oreilly.com/playlists/bd747aba-67d8-4218-8eb6-10b80951e766/


Video - Introduction to Python
https://learning.oreilly.com/videos/introduction-to-python/9781491904794

Video - Intermediate Pyton Programming
https://learning.oreilly.com/videos/intermediate-python-programming/9781491954935


Introducing GitHub, 2nd Edition
https://learning.oreilly.com/library/view/introducing-github-2nd/9781491981801/

If you’re new to GitHub, this concise book shows you just what you need to get started and no more. It’s perfect for project and product managers, stakeholders, and other team members who want to collaborate on a development project—whether it’s to review and comment on work in progress or to contribute specific changes. It’s also great for developers just learning GitHub.

Video - Learning GitHub
https://learning.oreilly.com/videos/learning-path-github/9781491972069/9781491972069-video257724


YouTube Math Channel - 3Blue1Brown
https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw


Think Stats, 2nd Edition
https://learning.oreilly.com/library/view/think-stats-2nd/9781491907344/

If you know how to program, you have the skills to turn data into knowledge, using tools of probability and statistics. This concise introduction shows you how to perform statistical analysis computationally, rather than mathematically, with programs written in Python. You’ll learn the entire process of exploratory data analysis—from collecting data and generating statistics to identifying patterns and testing hypotheses.


Think Bayes
https://learning.oreilly.com/library/view/think-bayes/9781491945407/

If you know how to program with Python, and know a little about probability, you’re ready to tackle Bayesian statistics. This book shows you how to use Python code instead of math to help you learn Bayesian fundamentals. Once you get the math out of the way, you’ll be able to apply these techniques to real-world problems.


Videos - Linear Algebra
https://ocw.mit.edu/courses/mathematics/18-06-linear-algebra-spring-2010/video-lectures/

Data Science from Scratch, 2nd Edition
https://learning.oreilly.com/library/view/data-science-from/9781492041122/

To really learn data science, you should not only master the tools—data science libraries, frameworks, modules, and toolkits—but also understand the ideas and principles underlying them. Updated for Python 3.6, this second edition of Data Science from Scratch shows you how these tools and algorithms work by implementing them from scratch.

News and Media Literacy
https://www.commonsensemedia.org/news-and-media-literacy/what-is-media-literacy-and-why-is-it-important


The Hard Thing About Hard Things: Building a Business When There Are No Easy Answers
https://www.amazon.com/Hard-Thing-About-Things-Building/dp/0062273205

Team of Teams: New Rules of Engagement for a Complex World
https://www.amazon.com/Team-Teams-Rules-Engagement-Complex/dp/1591847486


Phishing for Phools
https://medium.com/wordsthatmatter/phishing-for-phools-ad31b127cfa6

https://www.amazon.com/Phishing-Phools-Economics-Manipulation-Deception/dp/0691168318/

WTF?: What's the Future and Why It's Up to Us
https://learning.oreilly.com/library/view/wtf-whats-the/9780062565723/



* Packt Books

https://www.packtpub.com/free-learning

Learn Kali Linux 2019
https://subscription.packtpub.com/book/networking_and_servers/9781789611809

DevOps Paradox
https://www.packtpub.com/free-ebooks/reading-list/admin-and-networking/9781789133639

The Python Workshop - Nov 2019
https://subscription.packtpub.com/book/programming/9781839218859

Python Automation Cookbook - Second Edition - May 2020
https://subscription.packtpub.com/book/programming/9781800207080

Hands-On Network Programming with C - May 2019
https://subscription.packtpub.com/book/networking_and_servers/9781789349863

Extreme C - Oct 2019
https://subscription.packtpub.com/book/programming/9781789343625

Practical C Programming - Feb 2020
https://subscription.packtpub.com/book/programming/9781838641108

Hands-On System Programming with Linux - Oct 2018
https://subscription.packtpub.com/book/networking_and_servers/9781788998475


* Packt interactive courses

https://subscription.packtpub.com/interactive-courses

** Packt interactive python courses

https://subscription.packtpub.com/interactive-courses/programming/learn-python-programming

https://subscription.packtpub.com/interactive-courses/data/beginning-python

https://subscription.packtpub.com/interactive-courses/data/intermediate-python

https://subscription.packtpub.com/interactive-courses/data/data-science-projects-with-python

https://subscription.packtpub.com/interactive-courses/web-development/websites-with-python-flask

https://subscription.packtpub.com/interactive-courses/programming/building-a-blackjack-gui-in-python


* Articles / Blogs

Share Files Using Lightweight Http Servers in Linux
https://linuxhint.com/share_files_lightweight_http_server/


* Server Config

Configure Nginx SSL + force HTTP to redirect to HTTPS + force www to non-www
https://www.digitalocean.com/community/questions/configure-nginx-ssl-force-http-to-redirect-to-https-force-www-to-non-www-on-serverpilot-free-plan-using-nginx-configuration-file-only


* Jupyter Hub

https://jupyterhub.readthedocs.io/en/latest/

Jupyter Hub - Using a reverse proxy
https://jupyterhub.readthedocs.io/en/latest/reference/config-proxy.html
