#+AUTHOR:   Sebastian Emilio Narvaez
#+EMAIL:    snarvaezsoft at g mail dot com

#+OPTIONS: html-style:nil
#+HTML_HEAD:  <link rel='stylesheet' type='text/css' href='style.css' />
#+HTML_HEAD_EXTRA: <meta name='viewport' content='width=device-width, initial-scale=1.0' />

#+OPTIONS: toc:nil        (no default TOC)
#+INCLUDE:  "navigation.inc"
#+INCLUDE:  "simple_header.inc"
#+TOC: headlines 2        (insert TOC here, with two headline levels)
